### ISSUE TITLE
Управление пространством, ориентация в нем.

### ISSUE THREAD

**Issue by TeditMan** [khomiakov/semproj#2]
Управление не интуитивно понятно

**Comment by mrkraev** [comment]
1. Правильное вращение
2. Оптимизация управления. Возможно, какие-то пояснения по использованию, которые, к примеру, можно выводить на начальном экране.
3. Для ориентации удобно при наведении мыши на экран выводить координаты в каком-либо виде. Либо любым другим образом дать возможность пользователю понимать, на какую часть неба он смотрит.

**Comment by mrkraev** [comment]
Выполнено.
