### ISSUE TITLE
Преобразования

### ISSUE THREAD

**Issue by TeditMan** [khomiakov/semproj#3]
Механика проверки экрана на наличие звёзд в области вокруг чёрной дыры не реализована, как и вывод новой картинки.
Также в будущем input(), lensing() и output() нужно внести под условие if a.draw_black_hole is True

**Comment by mrkraev** [comment]
Выполнена задача относительно функций input1 и output. Смотри a374d5.

**Comment by TeditMan** [comment]
Done
