### ISSUE TITLE
Графики-2

### ISSUE THREAD

**Issue by TeditMan** [khomiakov/semproj#4]
Возможно стоит добавить словесное описание графиков при наведении мыши на них, или нажатии на соответствующую кнопку правой кнопкой мыши.

**Comment by mrkraev** [comment]
Я бы добавил, что стоит поправить масштаб окна, на котором появляются графики. И все еще не реализована возможность открывать несколько графиков сразу.

ps Возможно, не стоит разбивать настолько смежные задачи на отдельные issue.

**Comment by mrkraev** [comment]
Не будет реализовано.
