### ISSUE TITLE
Дополнительная визуализация.

### ISSUE THREAD

**Issue by mrkraev** [khomiakov/semproj#8]
В проекте достаточно плохо виден сам эффект: он то ли есть, то ли его и нет. Необходимы наглядные картинки, необязательно очень техничные.

**Comment by mrkraev** [comment]
У меня есть заготовки на эту тему, пока не удается привязать их к общим переменным.

**Comment by TeditMan** [comment]
Можно закрывать, вопрос с видимостью эффекта решён
